# Generated by Django 5.0.4 on 2024-05-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo_app", "0002_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="upload_time",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="user",
        ),
        migrations.AddField(
            model_name="photo",
            name="title",
            field=models.CharField(default="Default Title", max_length=100),
        ),
    ]
