# Generated by Django 4.2.11 on 2024-05-26 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("photo_app", "0003_remove_photo_upload_time_remove_photo_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("processed_image", models.ImageField(upload_to="processed_photos/")),
                (
                    "original_photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="photo_app.photo",
                    ),
                ),
            ],
        ),
    ]
