# Generated by Django 4.2.13 on 2024-06-02 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("photo_app", "0004_processedphoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="photo_app.user",
            ),
        ),
    ]
